version: 2
updates:
  - package-ecosystem: "devcontainers" 
    directory: "/"
    schedule:
      interval: daily
      
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: weekly
