version: 2
updates:
  - package-ecosystem: "devcontainers" 
    directory: "/.devcontainer/pre-build"
    schedule:
      interval: daily
      
  - package-ecosystem: "terraform"
    directory: "/coder-deployment/terraform"
    schedule:
      interval: weekly

  - package-ecosystem: "terraform"
    directory: "/coder-deployment/terraform_info"
    schedule:
      interval: weekly
