name: Test user_data.sh
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/test_user_data.yml'
      - './k8s/coder-deployment/terraform/scripts/user_data.sh'
    branches:
      - "main"



jobs:
  test_user_data:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1

    - working-directory: ./coder-deployment/terraform/scripts
      run: |
        apt update
        apt install curl -y
        sed -i "2a\\alias sudo=''" ./user_data.sh
        chmod +x ./user_data.sh 
        ./user_data.sh

    
